import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Login from "./login/page";
import NavSidebar from "./components/NavSidebar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-mainBg text-textColor">
        {2 > 1 ? (
          <NavSidebar>
            <div className="container mx-auto flex flex-col min-h-screen">
              <div className="flex-grow">{children}</div>
              <Footer />
            </div>
          </NavSidebar>
        ) : (
          <Login />
        )}
      </body>
    </html>
  );
}
