import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import Login from "./components/LoginForm";
import NavSidebar from "./components/NavSidebar";
import Footer from "./components/Footer";
import { auth } from "./auth/auth";
import { AuthContextProvider } from "./utils/userContext";

export const metadata: Metadata = {
  title: "Next Generation Dashboard",
  description: "Generated by Tambi Asawo",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await auth();

  return (
    <html lang="en">
      <body className="bg-mainBg text-textColor !overflow-x-clip">
        {user ? (
          <AuthContextProvider user={user}>
            <NavSidebar>
              <div className="container w-full xl:max-w-9xl xl:mx-auto flex flex-col min-h-screen !overflow-x-hidden">
                <div>{children}</div>
                <Footer />
              </div>
            </NavSidebar>
          </AuthContextProvider>
        ) : (
          <Login />
        )}
      </body>
    </html>
  );
}
