import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Login from "./login/page";
import NavSidebar from "./components/NavSidebar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {2 > 1 ? (
          <div className="flex gap-4">
            <NavSidebar>
              <div className="flex flex-col gap-2">
                {children}
                <Footer />
              </div>
            </NavSidebar>
          </div>
        ) : (
          <Login />
        )}
      </body>
    </html>
  );
}
